#!/bin/bash

# Install tools
brew install bat
brew install curlie
brew install ddh
brew install difftastic
brew install diskus
brew install dive
brew install dust
brew install exa
brew install fd
brew install fortune
brew install fselect
brew install fzf
brew install git-delta
brew install gitui
brew install glow
brew install golangci-lint
brew install htop
brew install hyperfine
brew install jid
brew install jq
brew install k9s
brew install kubernetes-cli
brew install lazydocker
brew install lazygit
brew install moreutils
brew install mosh
brew install octant
brew install ox
brew install procs
brew install ripgrep
brew install sd
brew install shellcheck
brew install tmux
brew install tokei
brew install vegeta
brew install watch
brew install watchexec
brew install xh
brew install yq
